
import: Activiti/activiti-scripts:.travis.java.yml@master
env:
  global:
    - ORG='activiti'
    - APP_NAME='activiti-cloud-identity'
    - GITHUB_CHARTS_REPO="https://${GITHUB_TOKEN}@github.com/Activiti/activiti-cloud-helm-charts.git"
    - RELEASE_BRANCH="develop"
    - HELM_VERSION=2.12.3
    - HELM_REPO_BASE_URL=https://kubernetes-charts.alfresco.com
    - HELM_REPO=stable
    - KUBERNETES_VERSION=1.14.8
    - TRAVIS_WAIT_TIMEOUT=${TRAVIS_WAIT_TIMEOUT:-180}
before_script:
  - echo -e "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com" >>  ~/.git-credentials
  - curl -s https://kubernetes-helm.storage.googleapis.com/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar zx
  - sudo mv linux-amd64/helm /usr/local/bin/
    
stages:
- name: verify
- name: releasechart
  if: branch = master
  
jobs:
  include:
  - name: Verify build
    stage: verify
    script:
    - cd charts/$APP_NAME && make build 
    
  - if: branch = master
    name: Create tag package helm chart and realease it
    stage: releasechart
    script: | 
      if [ "$TRAVIS_PULL_REQUEST" = "false" ]; 
      then
        cd charts/$APP_NAME ;
        make version ;
        make tag ;
        make release ;
        make github ;
        make updatebot/push-version ;
      fi

    
    
    
